[package]
authors = ["manguluka <tali@manguluka.com>"]
name = "geocode"
description = "Find location information."
version = "0.1.0"

[dependencies]
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
cabot = "0.1.3"
url = "1.5.1"
